Allow easy overriding of 'Unknown' in BooleanWidget
carltongibson/django-filter pull request #1268
Opened 2020-09-18 09:59 UTC by Real-Gecko

I've encountered situation where client wanted "Not selected" instead of "Unknown" so I had to copy paste entire class just to override the string. This little PR adds ability to easily override the text like this
```python
is_active = django_filters.BooleanFilter(widget=BooleanWidget(empty_label='Not selected'))
```

2020-09-28 19:26 UTC, michael-k commented on django_filters/widgets.py
> +        choices = (('', empty_label if empty_label else _('Unknown')),
```suggestion
        choices = (('', empty_label or _('Unknown')),
```

2020-10-09 04:58 UTC, Real-Gecko commented
Anyone?

2020-10-09 07:36 UTC, carltongibson requested changes
Thanks for the thought. This isn't worth the extra API. Just use a `Select` widget.

2020-10-09 07:36 UTC, closed without merging

2021-01-21 13:34 UTC, gatsinski commented
I opened a similar PR (#1217)  almost a year ago allowing custom choices. Not only the empty label but also for true and false.

I get your point and I agree we can just use `Select` widget but is it really not worth the extra API? Yes and No are not the only ways to say that something is True or False. If we are forced to settle with these predefined labels it will make the existence of `BooleanWidget` obsolete because we won't be able to use it for a lot of cases where it actually makes more sense than using Select widget. So we can then say that the whole `BooleanWidget` may not be worth the extra API. 

Django-filter is a library and as such it has to be flexible.

2024-06-16 15:13 UTC, Guilouf commented
I really dont get it, for `ChoiceField` we have the `empty_label` kwarg and `EMPTY_CHOICE_LABEL` setting, here https://github.com/carltongibson/django-filter/blob/main/django_filters/fields.py#L292,
but for `BooleanField` it's apparently out of question, as we also can see here: https://github.com/carltongibson/django-filter/issues/871
I can understand that you want a clean API, but why allow such options on some fields and not on the others @carltongibson ?

For future me or other people that struggle, example on how it have to be done as for now:
```python
from django.forms import  Select
from django_filters import BooleanFilter

nullable_boolean_choices = (
    (True, "Yes"),
    (False, "No"),
    (None, "Whatever"),
)

class SomeFilter(FilterSet):
    has_source = BooleanFilter(
        field_name='source',
        lookup_expr='isnull',
        widget=Select(choices=nullable_boolean_choices)
    )
```
In that example i want to filter objects that have at least one relation to a `Source` object, or no relation, or don't filter anything.
For what i tried it can't be done with a `ChoiceFilter` because of `isnull` not accepting strings.